footprint: [[-0.16, -0.16], [-0.16, 0.16], [0.16, 0.16], [0.16, -0.16]]
#robot_radius: 0.14
#max_obstacle_height: 3.0
#min_obstacle_height: -3.0
#inf_is_valid: true


static_layer:
  enabled: true
  map_topic: /map
  subscribe_to_updates: true

obstacle_layer:
  enabled: true
  obstacle_range: 5.0
  raytrace_range: 3.0
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  observation_sources: scan
  scan: {sensor_frame: laser_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true, inf_is_valid: true}

inflation_layer:
  enabled: true
  cost_scaling_factor: 12  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius: 1  # max. distance from an obstacle at which costs are incurred for planning paths.
